FROM node:26.6.0-alpine3.23@sha256:b528fccffe400ce6162162f70777bdfcd8439aa1affc2e8e2d66a0db2e018378 AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts && npm cache clean --force

FROM node:26.6.0-alpine3.23@sha256:b528fccffe400ce6162162f70777bdfcd8439aa1affc2e8e2d66a0db2e018378 AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=dependencies --chown=10001:10001 /app/node_modules ./node_modules
COPY --chown=10001:10001 dist ./dist
COPY --chown=10001:10001 package.json package-lock.json ./
USER 10001:10001
CMD ["node", "dist/apps/api.js"]
